apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: cicd
    repoURL: 'https://github.com/Spider-Art/CICD-ArgoCD-deployment.git'
    targetRevision: HEAD
